{{- /* chezmoi:modify-template */ -}}
{{- $lines := .chezmoi.stdin | splitList "\n" -}}
{{- $remainingLines := slice $lines (min (len $lines) 10) -}}
model_provider = "yescode"
model = "gpt-5.1-codex-max"
model_reasoning_effort = "high"

[model_providers.yescode]
name = "yescode"
base_url = "https://co.yes.vg/team/v1"
wire_api = "responses"
env_key = "YESCODE_API_KEY"

{{ join "\n" $remainingLines }}
